@startuml Use Case Diagram
  !define DARKBLUE
  !includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

  skinparam actorStyle awesome
  left to right direction
  
  'Creating actors
  actor MovieFanatic
  
  rectangle "Movieteka" {
    'Use cases
    usecase Add as "Add movie with info"
    usecase Display as "Display all movies with info"
    usecase Increment as "Increment watch counter
                          for movie"
    usecase Check as "Check movie in the list"

    MovieFanatic -- Add
    MovieFanatic -- Display
    MovieFanatic -- Increment
    Increment ..> Check : <<include>>
    Add ..> Check : <<include>>
  }

  note "info:\n - name\n - rating\n - watch counter" as note1

@enduml